version: "3.7"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "12_Sylvester"
      ACCEPT_EULA: "Y"
    networks:
            - webappnetwork
    links:
       - api-app
  api-app:
           container_name:  api-app
           image: image/api-app  
           restart: always
           build: .
           ports:
             - "7500:7500"
           networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge